### ISSUE TITLE
Type orderItem not in used

### ISSUE THREAD

**Issue by ShuTingY** [kxyoke/cs2102-fdsApp#30]

**Comment by kxyoke** [comment]
is used by `Orders` table in #24. init.sql changed accordingly as well.

**Comment by ShuTingY** [comment]
the change in the database will affect current implementation. Any change in the schema or init.sql can create an individual PR and request to merge first? Thank you

**Comment by ShuTingY** [comment]
I have made changes on my side also so we might need to solve merge conflict later on.
For the Order table I have also added a total for total cost for order

**Comment by ShuTingY** [comment]
Actually, I don't see the need of using the type now. Cus now the init only put 1 order Item.
I have tried your style an try to put more than 1 item inside. select those with more that one item in the array give me error.  
For myside, I am using 2-d array with id and qty. This seems easiler for me to work on. Because the add order part is on me side. So I would prefer just use 2-d array.

<img width="435" alt="image" src="https://user-images.githubusercontent.com/50542948/79015447-54be5e00-7b9f-11ea-850d-c127ca992e45.png">
<img width="524" alt="image" src="https://user-images.githubusercontent.com/50542948/79015472-61db4d00-7b9f-11ea-8384-6c92fb5cb59e.png">

**Comment by kxyoke** [comment]
ok can; I'll revert my Orders table so there won't be any merge conflicts there
