### ISSUE TITLE
[delete customer] Order table has foreign key reference to the usr_id on customer. Do we add delete on cascade?

### ISSUE THREAD

**Issue by ShuTingY** [kxyoke/cs2102-fdsApp#51]
Order table has foreign key reference to the usr_id on customer. Do we add delete on cascade? Or we add a trigger on if the customer delete the account , then the usr_id in the order table set to NULL or something like delete?

**Comment by kxyoke** [comment]
i think better `on delete set null` for stats purposes

**Comment by ShuTingY** [comment]
NOT ALLOW DELETION OF ACCOUNTS
