### ISSUE TITLE
[init.sql]  Is anyone updating the init.sql to valid data?

### ISSUE THREAD

**Issue by ShuTingY** [kxyoke/cs2102-fdsApp#58]
For my side, the init sql's data for promotion is random data so I cannot process the data and apply the promotion on the customer side.

**Comment by kxyoke** [comment]
Should we modify our part of the data to fit the respective criteria first (eg. at least 1 account with sufficient data, enough statistics etc.)?
Then after each of us have about sufficient data, we merge and check that there is no incorrect information?
@Dandford @hmtey
